package com.alsfirsova.domain.rest;

public enum Roles {
    ROLE_ADVERTISER,
    ROLE_ADVERTISER_EXTENDED,
    ROLE_ADVERTISER_SELF_REG,
    ROLE_VAT_CHECK_DISABLED,
    ROLE_MODERATION_OK,
    ROLE_PAYMENT_AVAILABLE,
    ROLE_PAYMENT_TYPE_PREPAY,
    ROLE_PAYMENT_ALLOWED,

}
